// Generated by diesel_ext
#![allow(unused)]
#![allow(clippy::all)]

use diesel::prelude::*;



#[derive(Queryable, Debug)]
pub struct Service {
    pub id: i32,
    pub nic_target_id: i32,
    pub port: i32,
    pub ip_proto_number: i32,
}

