// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use diesel::prelude::*;
#[derive(Queryable, Debug)]
pub struct Addres {
    pub id: i32,
    pub host_id: i32,
    pub network_id: i32,
    pub ip: String,
    pub ip_family: i32,
    pub netmask: i32,
    pub mac: Option<String>,
}

#[derive(Queryable, Debug)]
pub struct Host {
    pub id: i32,
    pub site_id: i32,
    pub name: String,
    pub os_type: Option<String>,
    pub hostname: Option<String>,
}

#[derive(Queryable, Debug)]
pub struct Network {
    pub id: i32,
    pub site_id: i32,
    pub name: String,
}

#[derive(Queryable, Debug)]
pub struct Note {
    pub id: i32,
    pub text: String,
    pub service_id: Option<i32>,
    pub address_id: Option<i32>,
    pub host_id: Option<i32>,
    pub network_id: Option<i32>,
}

#[derive(Queryable, Selectable, Debug)]
#[diesel(table_name = crate::schema::service)]
pub struct Service {
    pub id: i32,
    pub site_id: i32,
    pub address_id: i32,
    pub port: i32,
    pub ip_proto_number: i32,
    pub state: String,
    pub name: String,
    pub product: Option<String>,
    pub version: Option<String>,
    pub extra_info: Option<String>,
    pub os_type: Option<String>,
    pub device_type: Option<String>,
    pub hostname: Option<String>,
    pub confidence: Option<i32>,
    pub method: Option<String>,
    pub service_fp: Option<String>,
    pub cpe: Option<String>,
    pub rpcnum: Option<i32>,
    pub lowver: Option<i32>,
    pub highver: Option<i32>,
    pub owner: Option<String>,
}

#[derive(Queryable, Debug)]
pub struct Site {
    pub id: i32,
    pub name: String,
}

#[derive(Queryable, Debug)]
pub struct Tag {
    pub id: i32,
    pub name: String,
}

#[derive(Queryable, Debug)]
pub struct TagAssignment {
    pub id: i32,
    pub service_id: Option<i32>,
    pub address_id: Option<i32>,
    pub host_id: Option<i32>,
    pub network_id: Option<i32>,
    pub tag_id: i32,
}

// ── Insertable models ─────────────────────────────────────────────────────────

#[derive(Insertable)]
#[diesel(table_name = crate::schema::note)]
pub struct NewNote {
    pub text: String,
    pub service_id: Option<i32>,
    pub address_id: Option<i32>,
    pub host_id: Option<i32>,
    pub network_id: Option<i32>,
}

#[derive(Insertable)]
#[diesel(table_name = crate::schema::tag)]
pub struct NewTag {
    pub name: String,
}

#[derive(Insertable)]
#[diesel(table_name = crate::schema::tag_assignment)]
pub struct NewTagAssignment {
    pub tag_id: i32,
    pub service_id: Option<i32>,
    pub address_id: Option<i32>,
    pub host_id: Option<i32>,
    pub network_id: Option<i32>,
}
